base_url = "https://rust-lang.github.io/rustlings"
title = "Rustlings"
description = "Small exercises to get you used to reading and writing Rust code!"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "dracula"

insert_anchor_links = "heading"

[extra]
logo_path = "images/happy_ferris.svg"

[[extra.menu_items]]
name = "Home"
url = "/"
[[extra.menu_items]]
name = "Custom Exercises"
url = "/custom-exercises"

[[extra.footer_items]]
name = "Repository"
url = "https://github.com/rust-lang/rustlings"
