base_url = "https://rust-lang.github.io/rustlings"
title = "Rustlings"
description = "Small exercises to get you used to reading and writing Rust code!"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "dracula"

insert_anchor_links = "heading"

[extra]
logo_path = "images/happy_ferris.svg"

[[extra.menu_items]]
name = "Home"
url = "/"
[[extra.menu_items]]
name = "Setup"
url = "/setup"
[[extra.menu_items]]
name = "Usage"
url = "/usage"
[[extra.menu_items]]
name = "Q/A"
url = "https://github.com/rust-lang/rustlings/discussions/categories/q-a?discussions_q="
[[extra.menu_items]]
name = "Custom Exercises"
url = "/custom-exercises"

[[extra.footer_items]]
name = "Repository"
url = "https://github.com/rust-lang/rustlings"
[[extra.footer_items]]
name = "Changelog"
url = "https://github.com/rust-lang/rustlings/blob/main/CHANGELOG.md"
[[extra.footer_items]]
name = "MIT License"
url = "https://github.com/rust-lang/rustlings/blob/main/LICENSE"
